### ISSUE TITLE
user interface

### ISSUE THREAD

**Issue by felixmariotto** [danielesteban/blocks#1]
Again, nice project, this is promising !
The teleportation is very nicely done.

I think it would be a good thing to let the player pick a cube type, and a tool type (eraser, brush for painting existing block.. etc.. ). Also you might want an in-game menu to look for a game server for instance, or basic game parameters like sound.

I actually made a tool for VR user interfaces, check out the examples : https://three-mesh-ui.herokuapp.com/#keyboard
It's got some cool features like MSDF text, CSS-like syntax, a virtual keyboard...
If you're interested, I'm willing to help you code the user interface using this tool. (if you take contributions)

**Comment by danielesteban** [comment]
I did already check out your project when you posted it on the threejs forum. It's really nice.
I'll prolly will implement something like that when it's time to get serious with the UI.
But for now, I have enough with my current quick&dirty canvas texture based system.
I just need selecting a couple options, picking colors and simple stuff like that.
I agree my current UI situation could be way better haha.. but now I want to focus my efforts on adding some more new features.

**Comment by danielesteban** [comment]
BTW.. this is what I mean by my current canvas texture based system:
![ui](https://user-images.githubusercontent.com/806111/83328221-c18dd480-a281-11ea-8178-3748d394f926.gif)

**Comment by felixmariotto** [comment]
My bad, I actually didn't try to click on the menu button behind the hand. I tried again, it works smoothly and this is a smart idea to put it behind the hand. I would suggest making this menu button more obvious, but as you said this is not a priority.

Also the text is very pixelated, I think that's how you would benefit the most from three-mesh-ui, or at least get inspiration to make your own solution. ([MSDF text](https://three-mesh-ui.herokuapp.com/#msdf_text) uses a shader to render glyphs on plane geometries, it's both very efficient and very neat, try zooming in the example). The color picker however makes sense in canvas texture.

It looks like both events 'selectstart' and 'selectend' activate buttons, is that intentional ? I found it was not very intuitive.

**Comment by danielesteban** [comment]
Yeah. MSDF text seems like the way to go. Altough, the pixelated aliased fonts kinda fit with the art style. I dunno. All of the UI is just a temporary placeholder for developing the functionality.
I will revisit this once I finish the rest of the main stuff (or if the current system starts getting out hand).
