### ISSUE TITLE
Moon doesn't look like the moon

### ISSUE THREAD

**Issue by felixmariotto** [danielesteban/blocks#2]
I assume the green round thing I've seen in the sky is the Moon, it really got me thinking before I realised what it is ! Maybe just make it grey ?

**Comment by danielesteban** [comment]
Yeah.. That's actually the sun hehe.. But at night time, it's coloring makes it look pretty weird. I should prolly replace it with an actual white/gray moon for the night time. Need to work a bit more on the day/night cycle but first I have some other ideas in mind.
![image](https://user-images.githubusercontent.com/806111/83327759-8a69f400-a27e-11ea-829c-a9c9c9b72a99.png)
