### ISSUE TITLE
Moving the head with joystick

### ISSUE THREAD

**Issue by felixmariotto** [danielesteban/blocks#3]
I'm a fan of playing seated, and I know some people prefer it as well.
Can I suggest using the joystick for moving the camera manually ? As an option of course.
This way you can U-turn... Otherwise you're stuck in the forward direction !

**Comment by danielesteban** [comment]
This is already implemented.
You can toggle between the teleport and flying locomotion in the menu.
To display the menu: Hold the trigger and point to the back of your left hand.
The flying locomotion allows you to move in any direction with the right hand joystick + the orientation of the hand.
Additionally, in both modes you can also rotate the view in 45deg increments with the left hand joystick.

![flying](https://user-images.githubusercontent.com/806111/83327610-71147800-a27d-11ea-8c39-38a7c375486f.gif)

**Comment by felixmariotto** [comment]
OK, I didn't find the menu at my first try. It's pretty neat ! How do you control the flight up/down direction though ? Not possible yet ?

**Comment by danielesteban** [comment]
You can just point your hand up/down. And press forwards/backwards on the joystick.
It combines the orientation of the hand with the direction of the joystick,

**Comment by felixmariotto** [comment]
Intuitively that's what I tried, but it didn't seem to work : 
![512_64](https://user-images.githubusercontent.com/46470486/83332430-6ff24380-a29b-11ea-9b22-b19847f57ec5.gif)

**Comment by danielesteban** [comment]
Your hands always pointing straight forward. This is what I mean by "point up":
(I only using forwards/bacwards joystick here)
![flying (2)](https://user-images.githubusercontent.com/806111/83332704-eba0c000-a29c-11ea-8c1c-546547355fe8.gif)

**Comment by felixmariotto** [comment]
Mh I see...
Well from a first-time-user perspective it's not very intuitive IMO, I expected the direction of my gaze to control the direction of the translation. Actually the simplest controls for flight mode would be to always move in the player's gaze, and use the joystick only to determine the speed. Rotation would be done be looking right or left.

**Comment by danielesteban** [comment]
I had it before following the gaze. But after testing it with many other users and myself, it seemed to give motion sickness to a high percent of the people.
After changing it to follow the hand direction, almost nobody seemed to get sick anymore.
So that's why it is like that. I'll take your feedback into consideration, nonetheless.

**Comment by danielesteban** [comment]
Variable speed is kind of the same story. If it's not linear. People get sick.

**Comment by danielesteban** [comment]
Maybe I'll add a third locomotion mode for fearless users with strong VR legs hehe

**Comment by felixmariotto** [comment]
Anyway proposing several locomotion modes with options for speed is a good idea for accessibility. With VR you can't really make assumptions about how your game will be played. Even Half Life Alyx does that : https://half-life.com/en/alyx/vr

**Comment by danielesteban** [comment]
Yes, my dude. But it's all about priorities. I rather get onto things that bring value to everybody. Like grass, water physics, player skins, sand physics, world editing tools.. etc
Than get stuck on a loop developing 20 locomotion systems just to cater to a small percent of the users. I know I'll maybe keeping some users away by having just this two locomotion methods, but it's a gamble I'm willing to make. It's all about reducing scope. I'm striving for simplicity and prioritizing what brings more value to the most people.

**Comment by felixmariotto** [comment]
I 100% agree, I'm just emitting some ideas for later...
