### ISSUE TITLE
Improve/scale block type selection UX

### ISSUE THREAD

**Issue by danielesteban** [danielesteban/blocks#39]
Once #38 is done.. The current block selection UX is not gonna cut it.
I'm thinking to display the selected block type on the left hand instead of the word "Menu" and using the left-right stick to change between block types. Have to do some testing.. but I think something like that could scale to a larger number of block types.

 * [ ] Send blocktypes from servers to the clients on the INIT event.
 * [ ] Move atlas loading out of voxels class into the world class so it can be also used by this UI
 * [ ] Implement block selection UI in the client

**Comment by Pirovaleron54** [comment]
> Once #38 is done.. The current block selection UX is not gonna cut it.
> I'm thinking to display the selected block type on the left hand instead of the word "Menu" and using the left-right stick to change between block types. Have to do some testing.. but I think something like that could scale to a larger number of block types.
> 
>  * [x] Send blocktypes from servers to the clients on the INIT event.
>  * [x] Move atlas loading out of voxels class into the world class so it can be also used by this UI
>  * [x] Implement block selection UI in the client
>
